server:
  port: 9098
  
spring:
  application:
    name: gateway-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
   
      discovery:
        locator:
          enabled: true
      routes:
      - id: new-sale-service
        uri: http://localhost:8081
        predicates:
        - Path=/new-sale/**
        filters:
        - RewritePath=/new-sale/(?<path>.*), /$\{path}
        - AuthFilter
         
        
      - id: hsn-details-service
        uri: http://localhost:8083
        predicates:
        - Path=/hsn-details/**
        filters:
        - RewritePath=/hsn-details/(?<path>.*), /$\{path}
        - AuthFilter
        
      - id: user-management-service
        uri: http://localhost:8084
        predicates:
        - Path=/user-management/**
        filters:
        - RewritePath=/user-management/(?<path>.*), /$\{path}
        - AuthFilter
        
        
      - id: paymentgateway-service
        uri: http://localhost:8086/
        predicates:
        - Path=/paymentgateway/**
        filters:
        - RewritePath=/paymentgateway/(?<path>.*), /$\{path}
        - AuthFilter
 
        
      - id: inventory-service
        uri: http://localhost:9092/
        predicates:
        - Path=/inventory/**
        filters:
        - RewritePath=/inventory/(?<path>.*), /$\{path}
        - AuthFilter
     
     
      - id: connection-pool-service
        uri: http://localhost:8085/
        predicates:
        - Path=/connection-pool/**
        filters:
        - RewritePath=/connection-pool/(?<path>.*), /$\{path}
        - AuthFilter
        
        
      - id: ticket-management-service
        uri: http://localhost:9050/
        predicates:
        - Path=/ticket-tool/**
        filters:
        - RewritePath=/ticket-tool/(?<path>.*), /$\{path}
        - AuthFilter
      
     
       
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
        
      
          
        
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8762/eureka/

app:
 setWebEnvironment(false);

#
#
#####################properties related for aws cognito for authentication provider####################

Cognito:
     aws: 
        accesskey: AKIAYZOXA3O4HNGVWCQL
        secret_access_key: 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 
        client_id: 1tk6nn66mll5thvmgdlnuo54fi
        userpool_id: ap-south-1_gttd6A4tT
        region: ap-south-1
        idTokenPoolUrl: https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_gttd6A4tT
logging:
   level:
      org:
       springframework:
                security:
                       web:
                         FilterChainProxy : debug
    
###################################### End #################################################

encryption:
  enable: false